# redis-ha:
#   enabled: true

controller:
  replicas: 1

server:
  replicas: 1
  # service:
  #   type: LoadBalancer # Keep it commenteds otherwise Terraform cannot delete the ELB created using HELM

repoServer:
  replicas: 1

applicationSet:
  replicaCount: 1
  # replicaCount: 2